sudo: false
language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: npm release
    node_js: node
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email:
        secure: "fx3RUThdpCiYImPgkeVtcy8U9XqE6+L6maVgdrg5C6OQwq77xIFlsZ9/f1NhFdRSBHIVYqW/U2uvDNVGO9B9yGV/+caBoHO7FnSl07YdTNq3n6DxeovlGqHHMqYt7oB0EIcGUdF49DVpWwJwCZ3D2mwlE3U+16T3bgEs00/dx+16dSJ4xSh8YUzg7tBwdQpme7s1nUz/BxSD3awaxLRjfqDvFjSbb3LUT5ziNryNz1ofzVKqljJBrK+gTpNHb/XW26uO08gXlc80KUTeVCKy8q3m2yRx4DxrPqqHw9IY5GpHnVt+c6prHZ1LKC7nsHRZK31gQsGLdAg47NgNOjebqWjOPtUGnQarTWT8KYGaiYRedRQxgaMRGe1sSq469gWGJFCQykKNUVOKCes5p3fEGLsIMlQ+N6uBm3LwwSACyjrxnUOOPGDM3qMLYv7qU1+flfiWzsZCS096r1kH/pbCBjwCTzq0liUtbkFjE/TRSdAKHy7xNZWSvrGKY63oqY/Mqs+TgaiHv1W8Cv7XTjw9CDxA0ucdGIa9pIHM311XIVTi0qaJbcup6H4Fw/oxlq98Rj15woHrCZDkgot0MD94PQw8fSWD2pIjMDAwop6FHKOSj8YAAncvhLV+dnkcCHiKev2IV0zup3A5L59S4TQoNEDZo61r/YEyxD7y+2oEFyg="
      api_key:
        secure: "RmUqFxKPFBgmIyzjQLiA94dd3lqIVch/3j1itzYdNaKIuv9voM+tsbZlrlaIwpYZ4Ts81b0Y5FMzJbqemkKtvslZ/OBWiitPMVgE61V+Wjd/RhBX/qhqeXVg/QhPs1Rqp8IXVKM/578dqywnadBpeohja9ywB9iLr1jA+4dOGyuhRrJaBP7AJba1zTR46e/KXgARRtpoPD9wli0Zjoy8yjCjxqSzpOJrcWX6chL1wQ3M8Fcc6gY3PpHokoZNwrpaSQPVvYA+xkepgzZAgl749GIAj28Nr+d19tVgS+afnkHNmw8wW+3cr+kEeGAtg2VOrjF9umGg6eq29qX3O5Y4ionloVnyE1tD8dVHmiBDi69qcPosb8V8RQIe73Ref9fro4Z6tNJXl2SXF198XqJAOVLcecv4u7xxvDzWu6LZ7V50WCnYHUDQCqKSxdh6nMxPZw8OYgDMsASJMe6q+Hu1mt+dXgkhVlk7rx1lfyvDnYOHvWSLara6h2MYaFbnVh67xgDDShEhCQpZHRHnHY+AsgSiLVDUod5MpmaCcl34CyiOiZ38cPktdiH1PNGdc17AaQBQkBZF+qmo6jJZ8uOHlB9Q3ug/joO+5RWguWxjTxps0Iezi+JMFzGV8hqPvoo/IyMcauZCxQsGq6uzL6DeJg7XqjPp9UK8p8InkqhB4Ak="
      on:
        tags: true
        node: node
